<!DOCTYPE html>
<!-- Copyright 2020, Brigham Young University - Idaho. All rights reserved. -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CSE 111 - Prepare</title>
    <link rel="icon" type="image/png" href="../site/icon.png">
    <link rel="stylesheet" type="text/css" href="../site/style.css">
    <link rel="stylesheet" type="text/css" href="../site/hljs/vscode.css">
    <script src="https://www.gstatic.com/firebasejs/8.2.7/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.2.7/firebase-database.js"></script>
    <script src="../site/url.js"></script>
    <script src="../site/urlWrite.js"></script>
    <script src="../site/color.js"></script>
    <script src="../site/linenums.js"></script>
    <script src="../site/hljs/highlight.pack.js"></script>
</head>

<body>
<header>
    <div class="colorCtrl">&nbsp;</div>
    <div class="logo">
        <div class="upper">BYU</div>
        <div class="lower">Idaho</div>
    </div>
    <h2>CSE 111 | <span>Programming with Functions</span></h2>
</header>
<article>
    <h1>10 Prepare: Handling Exceptions</h1>
    <p>Errors and exceptional situations sometimes occur while a program
    is running. Such errors include a program attempting to read from a
    file that doesn't exist, a connection error when connecting to a
    server on a network, data that cannot be found on a server, and
    calculations that produce undefined results. A well written program
    doesn't crash when an error occurs but instead handles errors in a
    graceful manner that may include adjusting to an error, printing an
    error message for the user to see, and saving an error message to a
    log file. During this lesson, you will learn to write code that
    handles errors that may occur while your Python program is
    running.</p>

    <h2>Videos</h2>
    <p>Watch these two videos from Microsoft about error handling.</p>

    <ul class="videos long">
        <li><div><p><a href="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-17-of-44-Error-Handling">Error Handling Concepts</a> <span class="duration">(13 minutes)</span></p>
        <iframe src="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-17-of-44-Error-Handling/player" width="640" height="360" allowFullScreen title="Python for Beginners [17 of 44] Error Handling - Microsoft Channel 9 Video"></iframe>
        </div></li>

        <li><div><p><a href="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-18-of-44-Demo-Error-Handling">Error Handling Demonstration</a> <span class="duration">(4 minutes)</span></p>
        <iframe src="https://channel9.msdn.com/Series/Intro-to-Python-Development/Python-for-Beginners-18-of-44-Demo-Error-Handling/player" width="640" height="360" allowFullScreen title="Python for Beginners [18 of 44] Demo: Error Handling - Microsoft Channel 9 Video"></iframe>
        </div></li>
    </ul>

    <h2>Concepts</h2>
    <p>Here are the Python programming concepts and topics that you
    should learn during this lesson.</p>

    <ol class="long">
        <li><div>An <dfn>exception</dfn> is a relatively rare event that
        sometimes occurs while a Python program is running. For example,
        an exception occurs when a Python program tries to open a file
        for reading, and that file doesn't exist. There are many different
        <a href="https://docs.python.org/3/library/exceptions.html">built-in
        exceptions</a> that may occur while a Python program is
        running.</div></li>

        <li><div>When an exceptional event occurs, a Python function
        <dfn>raises</dfn> an exception which may be handled by code at
        another location in the executing Python program. The Python
        keyword to raise an exception is <code>raise</code>. Normally,
        you will not need to write code to raise an exception because
        the built-in functions, such as <code>open</code>,
        <code>int</code>, and <code>float</code>, will raise an
        exception when necessary.</div></li>

        <li><div>The Python keywords to handle exceptions are
        <code>try</code>, <code>except</code>, <code>else</code>, and
        <code>finally</code>. The following example code contains the
        outline of a complete try-except-else-finally block. Read the
        code and its comments carefully to understand the correct syntax
        and organization of a try-except-else-finally block.

<div class="pre"><pre class="linenums"></pre>
<pre class="python" id="ex1"># Example 1

<em>try</em>:
    # Write normal code here. This block must include
    # code that falls into two groups:
    # 1. Code that may cause an exception to be raised
    # 2. Code that depends on the results from the code
    #    in the first group
<em>except ZeroDivisionError as zero_div_err:</em>
    # Code that the computer executes if the code in the
    # try block caused a ZeroDivisionError to be raised.
<em>except ValueError as val_err:</em>
    # Code that the computer executes if the code in
    # the try block caused a ValueError to be raised.
<em>except (TypeError, KeyError, IndexError) as error:</em>
    # Code that the computer executes if the code in the try
    # block raised a TypeError, KeyError, or IndexError.
<em>except Exception as excep:</em>
    # Code that the computer executes if the code in the
    # try block caused any exception to be raised that was
    # not handled by one of the previous except blocks.
<em>except:</em>
    # Code that the computer executes if the code in the
    # try block caused anything to be raised that was
    # not handled by one of the previous except blocks.
<em>else:</em>
    # Code that the computer executes after the code
    # in the try block if the code in the try block
    # did not raise any exceptions.
<em>finally:</em>
    # Code that is executed after all the other code in
    # try, except, and else blocks regardless of whether
    # an exception was raised or not.</pre></div>

        <p>As shown in example&nbsp;1 above, when we want to write code
        that will handle exceptions, we first write a <code>try</code>
        block, and we put into that <code>try</code> block the normal
        code that might cause an exception. Then we write
        <code>except</code> blocks to handle the exceptions. Each
        <code>except</code> block may handle one type of exception such
        as:</p>
<div class="pre"><pre class="python">except ValueError as val_err:</pre></div>
        Or each <code>except</code> block may handle several types of
        exceptions, such as:
<div class="pre"><pre class="python">except (TypeError, KeyError, IndexError) as error:</pre></div>
Or one <code>except</code> block may handle all possible types of
exceptions such as:
<div class="pre"><pre class="python">except Exception as excep:</pre></div>
Or a bare <code>except</code> block may handle anything that can
be raised, including <code>SystemExit</code>,
<code>KeyboardInterrupt</code> and <code>GeneratorExit</code>
such as:
<div class="pre"><pre class="python">except:</pre></div>

        <p>The Python programming language requires us to order
        <code>except</code> blocks from most specific at the top to
        least specific (most general) at the bottom. However, in most
        programs, it is a bad idea to write <code>except</code> blocks
        that are very general, including an <code>except</code> block
        that handles all possible exception types and a bare
        <code>except</code> block.</p>

        <p>It is a bad idea to write an <code>except</code> block that
        handles all types of exceptions because such a block will handle
        <code>SyntaxError</code>. Normally, a program should not handle
        <code>SyntaxError</code>. Instead, a program should crash for a
        syntax error and print the line number where the syntax error
        occurred so that a programmer can find and fix the syntax error.
        Syntax errors are caused by a programmer mistyping code and not
        by bad user input or missing files. We want a programmer to find
        and fix all the syntax errors in a program long before the
        program is given to users.</div></li>

        <li><div>As shown at
        <span class="cross" data-ref="ex1">line&nbsp;26</span> in
        example&nbsp;1 above, following the <code>except</code> blocks,
        we may write an optional <code>else</code> block which the
        computer will execute if the <code>try</code> block does not
        raise any exceptions. It is uncommon to need to write code in
        the <code>else</code> block of <code>try</code> and
        <code>except</code>, and professional programmers almost never
        do it.</div></li>

        <li><div>As shown at
        <span class="cross" data-ref="ex1">line&nbsp;30</span> in
        example&nbsp;1 above, at the end of the exception handling code,
        we may write an optional <code>finally</code> block. The
        <code>finally</code> block contains code that the computer
        executes after all the other code in the <code>try</code>,
        <code>except</code>, and <code>else</code> blocks regardless of
        whether an exception was raised or not. The code in the
        <code>finally</code> block usually contains "clean up" code that
        frees resources that the code in the <code>try</code> block
        used. For example, if the code in the <code>try</code> block
        opens a file, the code in the <code>finally</code> block could
        close that file. In CSE&nbsp;111, you probably won't need to
        write a <code>finally</code> block.</div></li>
    </ol>

    <h2>Common Exception Types</h2>
    <p>There are many different types of
    <a href="https://docs.python.org/3/library/exceptions.html">built-in
    exceptions</a> that may occur while a Python program is running.
    This section shows how six types of exceptions may occur.</p>

    <h3>TypeError</h3>
    <p>The computer raises a <a href="https://docs.python.org/3/library/exceptions.html#TypeError"><code>TypeError</code></a>
    when the code that calls a function passes an argument with the
    wrong type. The code in example&nbsp;2 attempts to pass a string of
    text to the <code>round</code> function which causes the computer to
    raise <code>TypeError</code> as shown in the output below the code
    example.</p>

<div class="pre"><pre class="python" id="ex2"># Example 2

def main():
    try:
        integer = round("5.2")
        print(integer)

    except TypeError as type_err:
        print(type_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python type_error.py
type str doesn't define __round__ method</pre>

    <h3>ValueError</h3>
    <p>The computer raises a <a href="https://docs.python.org/3/library/exceptions.html#ValueError"><code>ValueError</code></a>
    when the code that calls a function passes an argument with the
    correct type but with an invalid value. A common event that causes
    the computer to raise a <code>ValueError</code> is when the
    <code>int</code> function or <code>float</code> function tries to
    convert a string to a number but the string contains characters that
    are not digits. The code in example&nbsp;3 and its output show a
    <code>ValueError</code>.</p>

<div class="pre"><pre class="python" id="ex3"># Example 3

def main():
    try:
        number = float(input("Please enter a number: "))
        print(number)

    except ValueError as val_err:
        print(val_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python value_error.py
Please enter a number: <span class="input">45.7u</span>
could not convert string to float: '45.7u'</pre>

    <h3>ZeroDivisionError</h3>
    <p>The computer raises a <a href="https://docs.python.org/3/library/exceptions.html#ZeroDivisionError"><code>ZeroDivisionError</code></a>
    when a program attempts to divide a number by zero (0) as shown in
    example&nbsp;4 and its output.</p>

<div class="pre"><pre class="python" id="ex4"># Example 4

def main():
    try:
        players = int(input("Enter the number of players: "))
        teams = int(input("Enter the number of teams: "))

        players_per_team = players / teams

        print(f"Each team should have {players_per_team} players.")

    except ZeroDivisionError as zero_div_err:
        print(zero_div_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python zero_div_error.py
Enter the number of players: <span class="input">20</span>
Enter the number of teams: <span class="input">0</span>
division by zero</pre>

    <h3>IndexError</h3>
    <p>If we write code that tries to use an index that doesn't exist in
    a list, when the computer executes that code, the computer will
    raise an <a href="https://docs.python.org/3/library/exceptions.html#IndexError"><code>IndexError</code></a>.
    The program in example&nbsp;5 creates a list that contains three
    surnames. Then the program attempts to change the surname at
    index&nbsp;3. Of course, this statement fails and causes the
    computer to raise an <code>IndexError</code> because the list
    contains only three elements, and the last index is 2.</p>

<div class="pre"><pre class="python" id="ex5"># Example 5

def main():
    try:
        # Create a list that contains three family names.
        surnames = ["Smith", "Lopez", "Marsh"]

        # Attempt to change the surname at index 3. Because there
        # are only three names in the surnames list and therefore
        # the last index is 2, this statement will fail and cause
        # the computer to raise an IndexError.
        surnames[3] = "Olsen"

    except IndexError as index_err:
        print(index_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python index_error_write.py
list assignment index out of range</pre>

    <p>The program in example&nbsp;6 is similar to example&nbsp;5, and
    both programs cause the computer to raise an
    <code>IndexError</code>. The program in example&nbsp;6 creates a
    list that contains three surnames. Then the program attempts to
    print the surname at index&nbsp;3. Of course, this statement fails
    because the list contains only three elements, and the last index is
    2.</p>

<div class="pre"><pre class="python" id="ex6"># Example 6

def main():
    try:
        # Create a list that contains three family names.
        surnames = ["Smith", "Lopez", "Marsh"]

        # Attempt to print the surname at index 3. Because there
        # are only three names in the surnames list and therefore
        # the last index is 2, this statement will fail and cause
        # the computer to raise an IndexError.
        print(surnames[3])

    except IndexError as index_err:
        print(index_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python index_error_read.py
list index out of range</pre>

    <h3>KeyError</h3>
    <p>If we write code that attempts to find a key in a dictionary and
    that key doesn't exist in the dictionary as shown in example&nbsp;7,
    then the computer will raise a <code>KeyError</code>.

<div class="pre"><pre class="python" id="ex7"># Example 7

def main():
    try:
        # Create a dictionary with student IDs as
        # the keys and student names as the values.
        students = {
            "42-039-4736": "Clint Huish",
            "61-315-0160": "Michelle Davis",
            "10-450-1203": "Jorge Soares",
            "75-421-2310": "Abdul Ali",
            "07-103-5621": "Michelle Davis"
        }

        # Attempt to find the key "50-420-1021",
        # which is not in the dictionary. This will
        # cause the computer to raise a KeyError.
        name = students["50-420-1021"]

        print(name)

    except KeyError as key_err:
        print(type(key_err).__name__, key_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python key_error.py
KeyError '50-420-1021'</pre>

    <p>Of course, it is very unlikely that a programmer would write a
    program that tries to find a hard-coded key that is not in a
    dictionary. However, it is common for a user to enter a key that is
    not in a dictionary. This is why the example code in lesson&nbsp;8
    includes an <code>if</code> statement above the line of code that
    searches the dictionary, like this:</p>

<div class="pre"><pre class="python">
    # Get a student ID from the user.
    id = input("Enter a student ID: ")

    # Check if the student ID is in the dictionary.
    <em>if id in students:</em>

        # Find the student ID in the dictionary and
        # retrieve the corresponding student name.
        name = students[id]

        # Print the student's name.
        print(name)

    else:
        print("No such student")</pre></div>

    <h3>FileNotFoundError</h3>
    <p>If we write a call to the <code>open</code> function that
    attempts to open a file for reading and that file doesn't exist, the
    computer will raise a <code>FileNotFoundError</code>. Example&nbsp;8
    contains code where such an error might occur.</p>

<div class="pre"><pre class="python" id="ex8"># Example 8

def main():
    try:
        with open("products.vcs", "rt") as products_file:
            for line in products_file:
                print(line)

    except FileNotFoundError as file_not_found_err:
        print(file_not_found_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python file_not_found.py
[Errno 2] No such file or directory: 'products.vcs'</pre>

    <h3>PermissionError</h3>
    <p>Nearly all computer operating systems, such as Microsoft Windows,
    Mac OS X, and Linux, allow multiple people to use a single computer.
    Because people need to store private data in files on a computer,
    the operating systems implement file access permission rules. These
    rules help to prevent unauthorized access to files.</p>

    <p>If we write a call to the <code>open</code> function that
    attempts to open a file and the person executing our program doesn't
    have permission to access the file, the computer will raise a
    <code>PermissionError</code>. Example&nbsp;9 contains code where
    such an error might occur.</p>

<div class="pre"><pre class="python" id="ex9"># Example 9

def main():
    try:
        with open("contacts.csv", "rt") as contacts_file:
            for line in contacts_file:
                print(line)

    except PermissionError as perm_err:
        print(perm_err)

if __name__ == "__main__":
    main()</pre></div>

<pre class="console">&gt; python permission_error.py
[Errno 13] Permission denied: 'contacts.csv'</pre>

    <h2>Example: Arithmetic</h2>
    <p>Example&nbsp;9 contains a complete program with
    <code>except</code> blocks to handle two types of exceptions:&nbsp;
    <code>ValueError</code> and <code>ZeroDivisionError</code>.</p>

<div class="pre"><pre class="python" id="ex9"># Example 9

"""
Sam, who is the owner of Sam's Sandwich Shop, requested
this program, which computes the number of sandwiches per
employee that were made in his restaurant in one day.
"""
def main():
    <em>try:</em>
        # Get the number of sandwiches made today and the
        # number of employees who worked today from the user.
        sandwiches = int(input("Number of sandwiches that were made today: "))
        employees = int(input("Number of employees who worked today: "))

        # Compute the number of sandwiches per employee
        # that were made today in the restaurant.
        sands_per_emp = sandwiches / employees

        # Print the results for the user to see.
        print(f"{sands_per_emp} sandwiches per employee")

    <em>except ValueError as val_err:</em>
        print()
        print(val_err)
        print("Error: you entered text that is not an integer.")
        print("Please run the program again and enter an integer.")

    <em>except ZeroDivisionError as zero_div_err:</em>
        print()
        print("Error: you entered 0 for the number of employees.")
        print("Please run the program again and enter an integer")
        print("larger than 0 for the number of employees.")


# Call main to start this program.
if __name__ == "__main__":
    main()</pre></div>

    <h2>Example: Reading from a File</h2>
    <p>The program in example&nbsp;10 below handles exceptions that
    might occur when the program opens and reads from a file. This
    program contains only one <code>try</code> block, which begins at
    <span class="cross" data-ref="ex10">line&nbsp;12</span> and includes
    all the regular code in the <code>main</code> function. This one
    <code>try</code> block has three <code>except</code> blocks at
    <span class="cross" data-ref="ex10">lines&nbsp;47,
    51,&nbsp;and&nbsp;55</span> that handle
    <code>FileNotFoundError</code>, <code>PermissionError</code>, and
    <code>ZeroDivisionError</code>.</p>

<div class="pre"><pre class="linenums"></pre>
<pre class="python" id="ex10"># Example 10

import csv

DATE_INDEX = 0
START_MILES_INDEX = 1
END_MILES_INDEX = 2
GALLONS_INDEX = 3


def main():
    <em>try:</em>
        # Open the fuel_usage.csv file.
        filename = "fuel_usage.csv"
        with open(filename, "rt") as usage_file:

            # Use the standard csv module to get
            # a reader object for the CSV file.
            reader = csv.reader(usage_file)

            # The first line of the CSV file contains headings
            # and not fuel usage data, so this statement skips
            # the first line of the CSV file.
            next(reader)

            # Print headers for the three columns.
            print("Date,Start,End,Gallons,Miles/Gallon")

            # Process each row in the CSV file.
            for row in reader:

                # From the current row of the CSV file, get
                # the date, the starting and ending odometer
                # readings, and the number of gallons used.
                date = row[DATE_INDEX]
                start_miles = float(row[START_MILES_INDEX])
                end_miles = float(row[END_MILES_INDEX])
                gallons = float(row[GALLONS_INDEX])

                # Call the miles_per_gallon function.
                mpg = miles_per_gallon(start_miles, end_miles, gallons)

                # Display the results for one row.
                mpg = round(mpg, 1)
                print(date, start_miles, end_miles, gallons, mpg, sep=",")

    <em>except FileNotFoundError as file_not_found_err:</em>
        print(f"Error: cannot open {filename}"
                " because it doesn't exist.")

    <em>except PermissionError as perm_err:</em>
        print(f"Error: cannot read from {filename}"
                " because you don't have permission.")

    <em>except ZeroDivisionError as zero_div_err:</em>
        print(f"Error: {filename} contains a"
                " zero in the gallons column.")


def miles_per_gallon(start_miles, end_miles, gallons):
    """Compute and return the average number of miles
    that a vehicle traveled per gallon of fuel.
    start_miles and end_miles are odometer readings in miles.
    gallons is a fuel amount in U.S. gallons.
    """
    mpg = abs(end_miles - start_miles) / gallons
    return mpg


# Call main to start this program.
if __name__ == "__main__":
    main()</pre></div>

    <h2 id="validate">Validating User Input</h2>
    <p>To <dfn>validate user input</dfn> means to check user input to
    ensure it is in the correct format before using that input. The
    program in example&nbsp;11 validates user input by handling
    exceptions. Notice in the <code>get_float</code> function at
    <span class="cross" data-ref="ex11">line&nbsp;28</span> there is a
    <code>try</code> block. The <code>try</code> block is part of a loop
    that validates user input in the <code>get_float</code> function.
    Notice at <span class="cross" data-ref="ex11">line&nbsp;43</span>
    that the <code>except</code> block handles
    <a href="https://docs.python.org/3/library/exceptions.html#ValueError"><code>ValueError</code></a>
    which is the type of exception that the
    <a href="https://docs.python.org/3/library/functions.html#float"><code>float</code></a>
    function raises when it tries to convert text to a number but the
    text contains characters that are not numeric.</p>

<div class="pre"><pre class="linenums"></pre>
<pre class="python" id="ex11"># Example 11

def main():
    gender = input("Enter your gender (M or F): ")

    weight = get_float("Enter your weight in kilograms: ", 20, 500)
    height = get_float("Enter your height in centimeters: ", 60, 250)
    age = get_float("Enter your age in years: ", 10, 120)

    bmr = basal_metabolic_rate(gender, weight, height, age)
    print(f"Your basal metabolic rate is {bmr} calories per day.")


def get_float(prompt, lower_bound, upper_bound):
    """Get a number from the user, validate that the user entered
    a number and not some other text, validate that the number is
    between a lower and upper bound, and then return the number. If
    the user enters an invalid number, this function will prompt
    the user repeatedly until the user enters a valid number.

    Parameters
        prompt: A string to display to the user.
        lower_bound: The smallest number that the user may enter.
        upper_bound: The largest number that the user may enter.
    Return: The number entered by the user.
    """
    while True:
        <em>try:</em>
            text = input(prompt)
            number = float(text)
            if number &lt; lower_bound:
                print(f"{number} is too small.")
                print("Please enter another number.")
            elif number &gt; upper_bound:
                print(f"{number} is too large.")
                print("Please enter another number.")
            else:
                # If the computer gets to this line of code, the
                # user entered a valid number between lower_bound
                # and upper_bound, so exit the loop.
                break

        <em>except ValueError as val_err:</em>
            # The user entered at least one character that is
            # not part of a floating point number, so print a
            # message asking the user to enter a number.
            print(f"{text} is not a number.")
            print("Please enter a number.")

    return number


def basal_metabolic_rate(gender, weight, height, age):
    """Calculate and return a person's basal metabolic rate (bmr)
    in calories per day. weight must be in kilograms, height must
    be in centimeters, and age must be in years.
    """
    if gender.upper() == "F":
        bmr = 447.593 + 9.247 * weight + 3.098 * height - 4.330 * age
    else:
        bmr = 88.362 + 13.397 * weight + 4.799 * height - 5.677 * age
    return bmr


# Call main to start this program.
if __name__ == "__main__":
    main()</pre></div>

    <h2>Tutorials</h2>
    <p>If the concepts above seem vague, these tutorials may clear some
    confusion for you:</p>

    <ul class="tutorials">
        <li><div>Python Exceptions: <a href="https://realpython.com/python-exceptions/">An Introduction</a></div></li>
        <li><div>Official Python <a href="https://docs.python.org/3/tutorial/errors.html">Errors and Exceptions tutorial</a></div></li>
        <li><div>The Most <a href="https://realpython.com/the-most-diabolical-python-antipattern/">Diabolical Python Antipattern</a></div></li>
        <li><div>Understanding the <a href="https://realpython.com/python-traceback/">Python Traceback</a></div></li>
    </ul>

    <p>The official Python <a href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions">built-in
    exceptions</a> reference contains a list of all the built-in
    exceptions. It also includes the <a href="https://docs.python.org/3/library/exceptions.html#exception-hierarchy">class
    hierarchy</a> for the built-in exceptions that is helpful for
    ordering <code>except</code> blocks from most specific to most
    general.</p>
</article>
<footer>
    <small>Copyright &copy; 2020, Brigham Young University - Idaho. All
    rights reserved.</small>
</footer>
</body>
</html>
